[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = admin
# Proxy configuration
proxy_mode = True
# Logging
logfile = /var/log/odoo/odoo-server.log
# SMTP
smtp_server = smtp-relay.brevo.com
smtp_port = 587
smtp_user = afc120001@smtp-brevo.com
smtp_password = MskLWNJDP6XE4aBv
smtp_ssl = False
